CREATE DATABASE HOTELPLUS;
USE HOTELPLUS;

CREATE TABLE USUARIO (
ID INT auto_increment,
NOME VARCHAR (100),
SOBRENOME VARCHAR (100),
EMAIL VARCHAR (100),
SENHA VARCHAR (100),
 PRIMARY KEY (ID, EMAIL)
);

CREATE TABLE HOTEIS (
ID INT auto_increment PRIMARY KEY,
NOME VARCHAR (100),
ENDERECO VARCHAR (250),
PROX_PRAIA VARCHAR (100),
ESTRELAS VARCHAR (50),
VALOR VARCHAR (100)
);

CREATE TABLE RESERVA (
ID_RESERVA INT auto_increment PRIMARY KEY,
ID_USUARIO INT,
ID_HOTEL INT,
NOME_USUARIO VARCHAR (100),
EMAIL_USUARIO VARCHAR (100),
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID),
FOREIGN KEY (ID_HOTEL) REFERENCES HOTEIS (ID),
DATA_ENTRADA VARCHAR(100),
DATA_SAIDA VARCHAR (100)
);



