CREATE DATABASE HOTELPLUS;
USE HOTELPLUS;

CREATE TABLE USUARIO (
ID INT auto_increment PRIMARY KEY,
NOME VARCHAR (100),
SOBRENOME VARCHAR (100),
EMAIL VARCHAR (100),
SENHA VARCHAR (100)
);

CREATE TABLE HOTEIS (
ID INT auto_increment PRIMARY KEY,
NOME VARCHAR (100),
ENDERECO VARCHAR (250),
PROX_PRAIA VARCHAR (100),
ESTRELAS VARCHAR (50),
VALOR VARCHAR (100)
);

select * from hoteis;

